### ISSUE TITLE
当columnsModel中出现重复的id的时候报错

### ISSUE THREAD

**Issue by xx7y7xx** [yyssc/ssc-grid#12]
Console中显示错误信息

```
Error: Objects are not valid as a React child (found: object with keys {id, code, name}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `GridRow`.
    at invariant (eval at <anonymous> (bundle.js:164), <anonymous>:39:15)
    at traverseAllChildrenImpl (eval at <anonymous> (bundle.js:752), <anonymous>:158:23)
    at traverseAllChildren (eval at <anonymous> (bundle.js:752), <anonymous>:186:10)
    at Object.instantiateChildren (eval at <anonymous> (bundle.js:776), <anonymous>:52:5)
    at ReactDOMComponent._reconcilerInstantiateChildren (eval at <anonymous> (bundle.js:770), <anonymous>:197:41)
    at ReactDOMComponent.mountChildren (eval at <anonymous> (bundle.js:770), <anonymous>:232:27)
    at ReactDOMComponent._createContentMarkup (eval at <anonymous> (bundle.js:644), <anonymous>:591:32)
    at ReactDOMComponent.mountComponent (eval at <anonymous> (bundle.js:644), <anonymous>:479:29)
    at Object.mountComponent (eval at <anonymous> (bundle.js:386), <anonymous>:37:35)
    at ReactDOMComponent.mountChildren (eval at <anonymous> (bundle.js:770), <anonymous>:241:44)
```

对应的输入值是：

```js
columnsModel = [
  {
    "id": "id",
    "lable": "主键",
    "datatype": 0,
    "length": 40,
    "digit": 0,
    "refinfo": null,
    "enumdata": null
  },
  {
    "id": "code",
    "lable": "编码",
    "datatype": 0,
    "length": 50,
    "digit": 0,
    "refinfo": null,
    "enumdata": null
  },
  {
    "id": "name",
    "lable": "名称",
    "datatype": 0,
    "length": 100,
    "digit": 0,
    "refinfo": null,
    "enumdata": null
  },
  {
    "id": "classifyid",
    "lable": "银行类别",
    "datatype": 5,
    "length": 40,
    "digit": 0,
    "refinfo": "G001ZM0000BASEDOCBANKCLASS0000000000",
    "enumdata": null
  },
  {
    "id": "description",
    "lable": "备注",
    "datatype": 0,
    "length": 400,
    "digit": 0,
    "refinfo": null,
    "enumdata": null
  },
  {
    "id": "classifyid",
    "lable": "账户性质",
    "datatype": 0,
    "length": 10,
    "digit": 0,
    "refinfo": null,
    "enumdata": null
  }
];
```

**Comment by xx7y7xx** [comment]
先强制类型转换吧。

**Comment by xx7y7xx** [comment]
先写测试用例

```
FAILED TESTS:
  <Grid>
    ✖ 应该正常渲染并且不报警告当id重复的时候
      Chrome 56.0.2924 (Linux 0.0.0)
    Invariant Violation: Objects are not valid as a React child (found: object with keys {id, code, name}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `GridRow`.
        at invariant (webpack:///~/fbjs/lib/invariant.js:39:0 <- test/index.js:2795:16)
        at traverseAllChildrenImpl (webpack:///~/react/lib/traverseAllChildren.js:158:0 <- test/index.js:15244:24)
        at traverseAllChildren (webpack:///~/react/lib/traverseAllChildren.js:186:0 <- test/index.js:15272:11)
        at Object.instantiateChildren (webpack:///~/react/lib/ReactChildReconciler.js:52:0 <- test/index.js:16144:6)
        at ReactDOMComponent._reconcilerInstantiateChildren (webpack:///~/react/lib/ReactMultiChild.js:197:0 <- test/index.js:15788:42)
        at ReactDOMComponent.mountChildren (webpack:///~/react/lib/ReactMultiChild.js:232:0 <- test/index.js:15823:28)
        at ReactDOMComponent._createContentMarkup (webpack:///~/react/lib/ReactDOMComponent.js:591:0 <- test/index.js:13015:33)
        at ReactDOMComponent.mountComponent (webpack:///~/react/lib/ReactDOMComponent.js:479:0 <- test/index.js:12903:30)
        at Object.mountComponent (webpack:///~/react/lib/ReactReconciler.js:37:0 <- test/index.js:7288:36)
        at ReactDOMComponent.mountChildren (webpack:///~/react/lib/ReactMultiChild.js:241:0 <- test/index.js:15832:45)
```

**Comment by xx7y7xx** [comment]
由于数据类型可以是任意，那么只好使用`String()`进行强制类型转换了。
