### ISSUE TITLE
Test with multiple node.js version

### ISSUE THREAD

**Issue by xx7y7xx** [yyssc/ssc-grid#5]
https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Choosing-Node-versions-to-test-against

https://www.appveyor.com/docs/lang/nodejs-iojs/#testing-under-multiple-versions-of-nodejs-or-iojs

**Comment by xx7y7xx** [comment]
在node.js 4.7.3会报错，暂停测试

```
$ npm test
> ssc-comp@0.13.0 test /home/travis/build/yyssc/ssc-grid
> npm run lint && npm run test-browser && npm run test-node
> ssc-comp@0.13.0 lint /home/travis/build/yyssc/ssc-grid
> eslint docs src test tools webpack *.js
> ssc-comp@0.13.0 test-browser /home/travis/build/yyssc/ssc-grid
> cross-env NODE_ENV=test karma start --single-run
18 02 2017 07:24:11.559:ERROR [config]: Invalid config file!
  Error: Cannot find module 'babel-runtime/core-js/json/stringify'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/yyssc/ssc-grid/webpack/base.config.js:6:18)
    at Module._compile (module.js:409:26)
    at loader (/home/travis/build/yyssc/ssc-grid/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/yyssc/ssc-grid/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/yyssc/ssc-grid/karma.conf.js:5:27)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
npm ERR! Linux 4.8.12-040812-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.7.3/bin/node" "/home/travis/.nvm/versions/node/v4.7.3/bin/npm" "run" "test-browser"
npm ERR! node v4.7.3
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! ssc-comp@0.13.0 test-browser: `cross-env NODE_ENV=test karma start --single-run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ssc-comp@0.13.0 test-browser script 'cross-env NODE_ENV=test karma start --single-run'.
npm ERR! This is most likely a problem with the ssc-comp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=test karma start --single-run
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ssc-comp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls ssc-comp
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/yyssc/ssc-grid/npm-debug.log
npm ERR! Test failed.  See above for more details.
```
