### ISSUE TITLE
[ValidateInput] TypeError: This library (validator.js) validates strings only

### ISSUE THREAD

**Issue by xx7y7xx** [yyssc/ssc-grid#94]
## Version
0.69.12

## Test Case

```jsx
      <ValidateInput
        type=""
        ref={(c) => validateInputRef = c}
        validators={[
          {type: 'decimal'},
          {
            type: 'custom',
            matchFunc: value => {
              return value <= 100 && value >= 0;
            },
            helpText: () => '残值率不能大于100%，小于0%',
          }
        ]}
        value={0}
      />
```

## Expected Behavior

no js error

## Actual Behavior

js error

```
    TypeError: This library (validator.js) validates strings only
        at assertString (webpack:///~/validator/lib/util/assertString.js:9:0 <- test/index.js:49369:12)
        at Object.isDecimal (webpack:///~/validator/lib/isDecimal.js:17:0 <- test/index.js:50488:31)
        at matchFunc (webpack:///src/utils/validation.js:16:0 <- test/index.js:48865:40)
        at webpack:///src/utils/validation.js:120:0 <- test/index.js:48992:20
        at Array.forEach (native)
        at Object.calcValidationState (webpack:///src/utils/validation.js:116:0 <- test/index.js:48987:15)
        at ValidateInput.setValidationState (webpack:///src/ValidateInput.js:74:0 <- test/index.js:106536:50)
        at ValidateInput.doValidate (webpack:///src/ValidateInput.js:66:0 <- test/index.js:106525:18)
        at Context.<anonymous> (webpack:///test/ValidateInputSpec.js:526:0 <- test/index.js:111432:46)
```

**Comment by xx7y7xx** [comment]
https://developer.mozilla.org/en/docs/Web/API/HTMLInputElement

<tr>
   <td><code>value</code></td>
   <td><code><em>string:</em></code> Returns / Sets the current value of the control.
    <p class="note"><strong>Note:</strong> If the user enters a value different from the value expected, this may return an empty string.</p>
   </td>
  </tr>
